version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${IMAGE_NAME}:latest
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    depends_on:
      - mongo
    networks:
      - db-network
      - frontend-network

  mongo:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    networks:
      - db-network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - frontend-network

  e2e:
    image: alpine:latest
    volumes:
      - ./e2e.sh:/e2e.sh
    command: sh -c "apk add --no-cache curl jq && chmod +x /e2e.sh && /e2e.sh"
    depends_on:
      - nginx
    networks:
      - frontend-network

volumes:
  mongodb_data:

networks:
  db-network:
    driver: bridge
  frontend-network:
    driver: bridge