FROM nginx:alpine

COPY nginx.conf /etc/nginx/nginx.conf.template
COPY static /usr/share/nginx/html/static

EXPOSE 80

CMD ["/bin/sh", "-c", "envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"]